portworx/kvdb

consul/kv_consul.go, mem/kv_mem.go, test/kv.go
I'm trying to write a test for https://github.com/libopenstorage/openstorage/pull/162 which uses the Mem datastore for testing, but I get errors in production because I'm using the Consul datastore instead.
Specifically, the [``mem.Enumerate`` never raises the ErrNotFound](https://github.com/portworx/kvdb/blob/master/mem/kv_mem.go#L202) whereas [``consul.Enumerate`` does](https://github.com/portworx/kvdb/blob/master/consul/kv_consul.go#L236) if required. This difference makes it hard to test the behavior of the library consumer when it's using the Consul datastore.
I updated the library to reflect this and updated the Enumerate tests to test this particular behavior. I tested the changes on an empty Consul instance but not with the Etcd backends (I have troubles building the tests …
=> Mem backend's Enumerate doesn't raise ErrNotFound

README.md, etcd/common/common.go, etcd/v2/kv_etcd.go
Additionally, cleaned up the 'go vet/lint' issues.
=> PWX-2776: Fixing type-cast issue for etcd2.Get() error

etcd/v3/kv_etcd.go
Add a Session to the Watch API.
The session can be used to detect etcd connection failures. 
With the new clientv3, the watch is hung if there etcd connectivity is lost
=> Handle etcd connection failures in etcd v3 watch API.

kvdb.go, mem/kv_mem.go, mem/kv_mem_test.go, test/kv.go
- Currently does not create a copy of the interface passed in Put, but simply stores it in the map.
- While returning in Get creates a byte array copy of the interface and returns the KVPair
A new API EnumerateWithSelector on its way.
=> Add a new type of kvdb mem which stores the values as interfaces instead of byte array.

consul/kv_consul.go, etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go, mem/kv_mem.go, test/kv.go
- For the following scenario the Snapshot API would panic for any kvdb implementation in snapMem.Delete function
Following is the timeline of calls that Snapshot API does
Time    API
t1 --> Watch
.
.
t2 --> Enumerate
.
t3 --> SnapPut
.
.
t4 --> Apply updates from Watch to snapDB
If there are any Delete calls to the actual kvdb between t1 and t2 those
keys will not be present in the Snapshot in-mem db. However the Watch will
record the Delete request. At t4 while applying the updates we will try to
Delete a non-existent key from snapMem and panic.
=> Fix a race condition in Snapshot implementation which caused a go panic.

etcd/v3/kv_etcd.go
- remove code duplication for modified index/value compare and set
- if server timeout is returned during update get value and check if
update went through. If modified index is different than ours and get value
is same as ours, we consider update was successful.
case compare and set if value matches:
this diff works fine if comparison is for value match
case compare and set if index matches:
if two or more updates with the same update value receive server timeout, its unclear how many of those updates went through. since the final update value is same, all of them will conclude that it was their update that went through. since the ultimate value of key is the same - i think this might be ok, after all no update is lost (except index may not be updated), still opening it for debate.
=> Handle server timeout during update

etcd/v3/kv_etcd.go
- We already have the logic to retry CAS when there is a grpc timeout.
- Extend it to retry for other error types.
=> Etcdv3: For CompareAndSet retry for all etcd server internal errors.

kvdb.go, test/kv.go
to get the currently set lock timeout. It is already implemented just needed to be added to interface.
=> Add GetLockTimeout

Dockerfile.kvdb, consul/kv_consul.go, consul/kv_consul_test.go, etcd/common/common.go, etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go, test/kv.go
- Change the CAD api to retry on a few errors.
- Add ErrStreamDrain/ErrConnClosing to thelist of errors we retry on. These are the errors return etcd 3.3.x and etcd 3.2.x resp when one of the nodes which the client is connected to goes down.
- Clean up few switch statements and collapse them.
=> Etcd v3: CompareAndDelete with retry.

consul/kv_consul.go, etcd/v3/kv_etcd.go, kvdb.go, mem/kv_mem.go, test/kv.go
When deleting tree, the prefix is a tree and not a random string.
=> Fix DeleteTree

etcd/v3/kv_etcd.go
There is a race between get/delete in this function, so its difficult to write a UT to test the race. deleteKey test however tests for non-existing key already.
=> Return ErrNotFound when deleting non-existing key

consul/client.go
removed logrus info mesg while connecting to consul server. this was contaminating pxctl output.
Signed-off-by: Saurabh Deoras <saurabh@portworx.com>
=> removed logrus info log

etcd/v3/kv_etcd.go
- While retrying CAS or CAD, we make a Get request. However this Get is made with a key
which has the domain added to the actual key. The Get API also adds the domain and we try to
fetch a non-existant key resulting into Get returning ErrNotFound (a non retryable error)
=> Etcdv3: In CAS & CAD pass in the kvp.Key without the domain to the Get call

bolt/kv_bolt_Test.go, consul/kv_consul_test.go, etcd/common/common.go, etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go, mem/kv_mem_test.go, test/kv.go
=> Etcdv3 CAD: Create a new context for every retry.

etcd/v3/kv_etcd.go
- Print the Modified index when Lock or CAS API fails.
- Etcd v3 does not guarantee that it will send a Cancel WatchResponse before stopping the watch.
- Whenever watch is now closed we send a ErrWatchStopped to callback.
=> Etcdv3 Watch: Handle closing of watch response channel

etcd/v3/kv_etcd.go
- With this change all the kvdb APIs except for (Create/Update/Delete) have retryable
etcd client requests.
=> Etcdv3: Add retries for lease requests

consul/kv_consul.go, etcd/v2/kv_etcd.go
if watch returns errors before getting all updates, return error on snapshot,
else snapshot will hang.
=> Watch errors during snapshot

mem/kv_mem.go
These log lines get printed for every put in mem kv and are not required.
=> Mem KV: Remove unnecessary log line in Put API

etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go, test/kv_controller.go
- Take a lock over the maintence client for etcd v3.
- Modified the existing testMemberStatus UT to
- start 5 node etcd cluster
- stop 2 nodes
- spin 16 goroutines and check status of all the 5 members
- only the 2 stopped nodes should be unhealthy.
- If the lock is removed the testMemberStatus UT will fail.
=> Etcdv3: Add a lock over etcd's maintenance client.

etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go
- Add a few more logs for clarity during error scenarios.
=> Etcdv3: Print the owner of the lock during error conditions

etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go, kvdb.go, kvdb_controller_not_supported.go, test/kv_controller.go
- Add a new API to run defragment in Kvdb interface/
- Use MaintenanceContext with no leader for Status APIs.
- Fix a bug in the isRetryNeeded function.
- Do not set the keep alive timeout for maintenance client as it is only used for Status API.
=> Etcdv3: Maintenance client changes. Add Defragment API.

etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go, kvdb.go, kvdb_controller_not_supported.go, test/kv_controller.go
PR comprises of two changes
1. Retry logic
```
Etcd v3 returns both types of errors
1. context.DeadlineExceeded
log line: kvdb error: context deadline exceeded, retry count: 0
2. grpc error code = DeadlineExceeded
log line: cas: get after retry failed with error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
2. Add a new field ID in the MemberInfo struct.
=> Add retry on grpc.ContextDeadlineExceeded. Change RemoveMember API

etcd/v3/kv_etcd.go
1. Send an ErrWatchStopped to the caller only once.
- Currently ErrWatchStopped gets sent to the caller multiple
times causing a resubscribing watch to fail as well.
2. Use context with leader requirement for Watch API.
- By default the etcd watchers will hang in case of a network partition and they are connected
to the minority.
- As mentioned here - https://github.com/etcd-io/etcd/issues/7247#issuecomment-276154894
setting the leader requirement for watchers allows them to switch to the majority partition.
=> Etcdv3: Watch API Improvements

etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go
- For most of the APIs which use TTLs, we create a lease with etcd.
The lease request previously had a timeout of 10 seconds, before it retried.
However lease is also used for the Lock API, which holds a lock for 16 seconds.
If we wait for 10 seconds to retry for a lease, the caller is bound to loose
the lock
- This change reduces the lease request timeout to 2 seconds.
=> Set lease request timeout to 2 seconds.

test/kv_controller.go
This PR is mainly for understanding how codecov.io displays the code coverage report for each PR submitted to this repo.
=> Add more kvdb controller UTs.

bolt/kv_bolt.go, common/common.go, common/common_test.go, consul/kv_consul.go, etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go, kvdb.go, mem/kv_mem.go, test/kv.go
- Instead of enumerating the whole kvdb tree, now the Snapshot API takes in a list
of prefixes. A snapshot is taken only on those prefixes.
- This helps in reducing long range queries which etcd does not like.
- If etcd is unstable or running on a slow disk, enumerating the whole tree can sometimes return errors/timeouts
- This will reduce the time taken for the Snapshot API to complete as well.
- Modified the UT to
- test the snapshot api on multiple prefixes
- at the same time do updates to a prefix which is not snapshotted
=> Improve the kvdb.Snapshot API.

bolt/kv_bolt.go, consul/kv_consul.go, etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go, kvdb.go, mem/kv_mem.go, test/kv.go, zookeeper/kv_zookeeper.go
- If the consistent flag is not true, then a Watch is not started in the Snapshot API.
=> Add consistent boolean to Snapshot API.

etcd/v3/kv_etcd.go, test/kv_controller.go
- Retry RemoveMember operation if it fails on unknown errors.
- Check if the error returned is not ErrMemberNotFound.
- Return nil for members that do not exist.
=> RemoveMember: Retry remove member in case of a failure

bolt/kv_bolt.go, consul/kv_consul.go, etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go, kvdb.go, mem/kv_mem.go, wrappers/kv_log.go, wrappers/kv_no_quorum.go, zookeeper/kv_zookeeper.go
- The existing EnumerateWithSelect API returns the actual interface values.
- The new EnumerateKVPsWithSelect API is similar but will return actual KVPairs instead.
=> Add EnumerateKVPWithSelect API.

Gopkg.lock, Gopkg.toml, api/bootstrap/bootstrap.go, api/bootstrap/k8s/k8s.go
- Porting the BootstrapEntry from porx to here so external clients reading this data can unmarshall it
- Verified manually golint passes on the new package.
Signed-off-by: Harsh Desai <harsh@portworx.com>
=> Add BootstrapEntry data structure to kvdb API

etcd/v3/kv_etcd.go, kvdb.go, kvdb_controller_not_supported.go, test/kv.go, test/kv_controller.go, wrappers/kv_log.go, wrappers/kv_no_quorum.go
Currently the etcd implementation accepts ip+port pair and builds a url with the http scheme. Use endpoint parameter instead of ip+port pair, this provides a way to build the etcd url on the user side with a custom scheme.
Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>
=> etcd: use endpoint parameter instead of the ip+port pair

etcd/v3/kv_etcd.go, etcd/v3/kv_etcd_test.go
The `etcd3.Keys()` method was FAILING when user-authentication was turned on:
* switched from `--from-key` to `--prefix` handling  (see test-results below)
* "stop-condition" no longer an issue, so we could reduce the # of retrievals from etcd
Closes # PWX-21389
**Test case**
Setup:
```bash
etcdctl user add root	# set password 'Password1' when prompted
etcdctl user add zox	# set password 'FooBar' whem prompted
etcdctl --user root:Password1 user grant-role root root
etcdctl --user root:Password1 auth enable
etcdctl --user root:Password1 role add pwx
etcdctl --user root:Password1 user grant-role zox pwx
etcdctl --user root:Password1 role grant-permission pwx readwrite …
```
=> PWX-21389: `etcd3.Keys()` fix and optimization

bolt/kv_bolt.go, consul/client.go, consul/kv_consul.go, etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go, kvdb.go, mem/kv_mem.go, test/kv.go, wrappers/kv_log.go, wrappers/kv_no_quorum.go, zookeeper/kv_zookeeper.go
The consumer may want to control when a kvdb gets compacted. Added a method
to do that. Implemented the new method for etcd v3.
Fixed a few static-check warnings.
Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>
PWX-21544
The static-check fixes should not be causing any change in the logic.
=> PWX-21544: add a method to run compaction on the KVDB

etcd/v3/kv_etcd.go
Signed-off-by: Jose Rivera <jose@portworx.com>
To Support IPv6 we need to add the IPv6 localhost '::1'.  
Closes #
PWX-23111
=> PWX-23111: Add IPv6 localhost '::1' as a defaultMachine.

etcd/v3/kv_etcd.go
Populate the revision of the key that was just created. This may be
useful for some clients.
Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>
PWX-23502
=> PWX-23502: populate the revision info after creating a key

.travis.yml, etcd/v3/kv_etcd.go, test/kv_controller.go
* will use configured KVDB endpoints first, for etcd3's ListMembers()
- the client-URLs from MemberList() will be used as fail-back, to get status for members that were not registered as endpoints
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
The `ListMembers()` API for Etcd-v3 calls `MemberList()` first, then implicitly uses `Status()` on each ClientURL
* the issue with this is that server-side EtcD might be configured differently than provided client-endpoints  (e.g. use cluster-only hostnames/IPs, that are not accessible by the KVDB-clients)
FIX:
* we will inquire about the member's `Status()` by using the configured client-endpoints first
* if we didn't get all the members, as a failback we'll use `MemberList()` -provided endpoints to …
=> PWX-20808: etcd3 members list fix

.travis.yml, etcd/common/common.go, etcd/v3/kv_etcd.go
* adding `IsTLSEnabled()` into etcd-common
- `IsTLSEnabled()` returns TRUE if `options[TransportScheme]=https`, or if client SSL cert was provided
* the EtcD endpoint URLs will be prefixed either with http:// or https://
Signed-off-by: Zoran Rajic <zrajic@purestorage.com>
ISSUE:
* without this fix, the kvdb library always constructs non-SSL endpoints -- which is **wrong** if kvdb is running in SSL-mode
FIX:
* the caller can explicitly set `options[TransportScheme]=https` to enable SSL support, also
* if caller supplied end-client SSL certs, we'll also automatically enable SSL support
Closes # PWX-27551  (part 1)
This fix will be combined with the "part 2" fix in the …
=> PWX-27551-pt1: SSL fixes (kdb)

bolt/kv_bolt.go, common/common.go, consul/kv_consul.go, etcd/v2/kv_etcd.go, etcd/v3/kv_etcd.go, kvdb.go, mem/kv_mem.go, test/kv.go, wrappers/kv_log.go, wrappers/kv_no_quorum.go, zookeeper/kv_zookeeper.go, zookeeper/kv_zookeeper_test.go
Configmap apis were used in vSphere provider which stopped px from
coming up on Nomad. The following changes are made
- Store interface moved to cloudops
- DriveSetStore interface created with Store as composite. Contains
interfaces with DriveSet datastructure.
- GetLockTryDuration introduced
- Renamed GetLockTimeout/SetLockTimeout to
GetLockHoldTimeout/SetLockHoldTimeout.
- Implemented IsKeyLocked() and LockWithKey() interfaces in kv_store
- Removed noOpStore implementation. It was a stop gap solution for
locak of implementation in kv_store
Closes #
=> PWX-28882: Fix Nomad support issues for vSphere provider

etcd/v3/kv_etcd.go, kvdb.go, kvdb_controller_not_supported.go, test/kv.go, test/kv_controller.go, wrappers/kv_log.go, wrappers/kv_no_quorum.go
ListMembers API
- The ListMembers API used to return a map[string]*MemberInfo. The key to this map was the name of a member.
- However when there is unstarted etcd member, the name of the member is set to empty.
- Changed the API to return a map[uint64]*MemberInfo, where the key is a unique ID which is always set (even for unstarted members).
- Also added HasStarted and Name fields to MemberInfo for easy lookup.
RemoveMemberByID API
- Introduced a new API to remove members based on their IDs.
UTs
- Fixed existing UTs to handle the new API.
- Added tests for RemoveMemberByID API.
- Added more checks to existing UTs.
Closes #
=> PWX-28113: Fix ListMembers API and add a new RemoveMemberByID API.

etcd/v3/kv_etcd.go, kvdb.go, kvdb_controller_not_supported.go, mock/mock_kvdb.go, wrappers/kv_log.go, wrappers/kv_no_quorum.go
Adding as a learner provides better stability as per the etcd docs. Caller is responsible for promoting the learner to a full voting member.
PWX-30451
=> PWX-30451: allow adding a new etcd member as a learner

.travis.yml, etcd/v3/kv_etcd.go
We want to preserve the old behavior of the New() blocking until the underlying connection is established.
Also, changed dist to focal in travis config to avoid build failure.
PWX-30841
=> PWX-30841: use WithBlock in etcd v3 client config

etcd/common/common.go
caFile option has been removed in etcd 3.4. So, pass caFile as trustedCAFile to avoid breaking clients.
PWX-31462
no testing done yet
=> PWX-31462: use caFile option if trustedCAFile is not provided

etcd/v3/kv_etcd.go
After addMember() to etcd4, this PR explicitly adds new member to memberlist returned by ETCDv4 if it is missing.
We have observed that after adding a new learner node to existing ETCD cluster (Probably, because of https://github.com/etcd-io/etcd/issues/11198 which is fixed in ETCD v3.5), this new learner node does 
not appear in memberlist immidately. Since, we get no error while adding a member, its safe to add to list of members .
(We are currently on ETCD v3.4.24)
Closes #
=> [PWX-32578] Explicitly add new member to initial-cluster if missing in memberlist

etcd/v3/kv_etcd.go
An error is returned when GetVal() returns an error
Closes #
=> Return error when GetVal gives error
