- consul/kv_consul.go
- etcd/v2/kv_etcd.go
- etcd/v3/kv_etcd.go
- kvdb.go
- mem/kv_mem.go
- test/kv.go
Adding the support for the `kvdb.Keys()` call.
> Implementing Keys() API call

- etcd/v3/kv_etcd.go
- test/kv_controller.go
- For older etcd versions, when a member was offline the CLientURLs for it will be returned as NULL.
- In v3.2.15 this behavior has changed and the API always returns ClientURLs.
- Add a unit test to check a member status in ControllerTests
- Separate out kvdb binary installations from the build container.
> ListMembers API should return correct health status and empty ClientURL.

- etcd/common/common.go
Signed-off-by: Paul Theunis <paul@portworx.com>
Parse given url.
Check for the scheme. 
If https is expected but no certs are given we pass an empty tls.Config object.
> PWX-5680: Fix etcd when using https and username:password but no certs

- consul/kv_consul.go
this pr loops over all possible consul end points till we successfully connect, or eventually error out.
Signed-off-by: Saurabh Deoras <sdeoras@gmail.com>
> PWX-5722: bug fix for connecting to multiple consul end points

- consul/kv_consul.go
minor update on a recent change made in PR #36 , while checking kv, just get version
Signed-off-by: Saurabh Deoras <sdeoras@gmail.com>
> kv check logic changed for consul

- consul/kv_consul.go
Signed-off-by: Saurabh Deoras <sdeoras@gmail.com>
> log error dont return

- consul/client.go
> Revert "removed logrus info log"

- consul/client.go
- consul/kv_consul.go
- kvdb.go
this pr is to enable tls in consul
Signed-off-by: Saurabh Deoras <saurabh@portworx.com>
> PWX-3992: enable tls in consul

- consul/kv_consul.go
consul does not support session ttl > 1 day.
Signed-off-by: Saurabh Deoras <saurabh@portworx.com>
> PWX-6375: upper ttl limit for consul sessions

- etcd/v3/kv_etcd.go
if watch errors out because etcd closed session, snapshot function should error out.
since kvdb index is always greater than 0, remove separate boolean.
> snapshot: handle watch closing

- .travis.yml
- Makefile
- README.md
- etcd/v3/kv_etcd.go
- kvdb.go
- kvdb_controller_not_supported.go
- test/kv_controller.go
- UpdateMember can be used to change the ip address or the port number of a member.
- Add a UT for UpdateMember.
> Kvdb Controller -  Add API UpdateMember.

- consul/client.go
also increase the number of retries.
> handle temporary name resolution errors

- etcd/v3/kv_etcd.go
- ETCD client has a bug in its failover/connection code where it fails to connect a secure etcd cluster
if the first endpoint is down.
- The change is to shuffle the list of endpoints and try connecting again. This is done regardless of
what error is returned when connecting for the first time.
- Not doing this for non-secure etcd, as this is already handled by the etcd client.
- ETCD has fixed this problem in the recent releases, but that involves changing grpc dependencies. Hence this is a stop gap solution.
More details here: https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#known-issue-etcd-client-balancer-with-secure-endpoints
Known issue: All the watches exit if the first endpoint goes down.
> Shuffle the list of secure etcd endpoints if the client fails to connect to first endpoint.

- wrappers/kv_no_quorum.go
otherwise clients keep trying in a loop.
> delay watch when not in quorum.

- etcd/v3/kv_etcd.go
since the lease may expire, causing the retry to fail.
> take the lease inside the retry loop.

- kvdb.go
Add details to error message to be more helpful.
> improve error message.

- etcd/v3/kv_etcd.go
- kvdb.go
- kvdb_controller_not_supported.go
- test/kv.go
- test/kv_controller.go
- wrappers/kv_log.go
- wrappers/kv_no_quorum.go
> PWX-28113: Adding the ListMembers & RemoveMemberByIP changes back

- etcd/v3/kv_etcd.go
- test/kv.go
> Change error message in LockWithTimeout and write UT for the same

- etcd/v3/kv_etcd.go
- kvdb.go
> PWX-36887: added a field to indicate if member is a learner

- etcd/v3/kv_etcd.go
> PWX-37961: In unlock don't write to the channel

- etcd/v3/kv_etcd.go
If the caller has asked us to Unlock the key, we can safely stop refreshing the lock even if we could not delete the key in kvdb. The lock will expire automatically.
PWX-37961
> PWX-37961: stop refreshing the lock unconditionally in kvdb.Unlock()

- etcd/common/common.go
- etcd/v3/kv_etcd.go
- etcd/v3/kv_etcd_test.go
Also, don't do CompareAndDelete if the key is unlocked already
PWX-37961
> PWX-37961: add unit tests for Unlock
